# -*- coding: utf-8 -*-
"""pdfsummarizer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14EuFE76W2o5qNmdZ1YiYgJQIsCpXvxdI
"""

!pip install openai pypdf

from google.colab import files
uploaded = files.upload()

import os
from pypdf import PdfReader
from openai import OpenAI

# 🔑 Paste your API key here
client = OpenAI(api_key="OPENAI-API-KEY"
def extract_text_from_pdf(file_path):
    reader = PdfReader(file_path)
    text = ""
    for page in reader.pages:
        text += page.extract_text() or ""
    return text

def summarize_text(text):
    text = text[:8000]  # keep within limits

    response = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[
            {"role": "system", "content": "Summarize clearly in bullet points."},
            {"role": "user", "content": text}
        ]
    )

    return response.choices[0].message.content

# 👉 Get uploaded file name
file_name = list(uploaded.keys())[0]

text = extract_text_from_pdf(file_name)
summary = summarize_text(text)

print("\n--- SUMMARY ---\n")
print(summary)